import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/ui/navigation/navbar";
import Footer from "./components/ui/navigation/footer";

export const metadata: Metadata = {
    title: "Notey",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <Navbar />
                <main className="w-[100%] h-[100%] flex flex-col justify-center items-center">
                    {children}
                </main>
                <Footer />
            </body>
        </html>
    );
}
